# Generated by Django 4.2.9 on 2024-01-03 10:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0002_mapstate_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapstate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
